// استيراد مكتبة emoji-flags

// تعريف قائمة الدول بدون الأعلام
export const countries = [
  // الدول العربية
  { value: 'ae', label: 'الإمارات العربية المتحدة' },
  { value: 'sa', label: 'المملكة العربية السعودية' },
  { value: 'eg', label: 'مصر' },
  { value: 'jo', label: 'الأردن' },
  { value: 'kw', label: 'الكويت' },
  { value: 'bh', label: 'البحرين' },
  { value: 'om', label: 'عُمان' },
  { value: 'qa', label: 'قطر' },
  { value: 'lb', label: 'لبنان' },
  { value: 'iq', label: 'العراق' },
  { value: 'ye', label: 'اليمن' },
  { value: 'ps', label: 'فلسطين' },
  { value: 'sy', label: 'سوريا' },
  { value: 'sd', label: 'السودان' },
  { value: 'ly', label: 'ليبيا' },
  { value: 'tn', label: 'تونس' },
  { value: 'dz', label: 'الجزائر' },
  { value: 'ma', label: 'المغرب' },
  { value: 'mr', label: 'موريتانيا' },
  { value: 'so', label: 'الصومال' },
  { value: 'dj', label: 'جيبوتي' },
  { value: 'km', label: 'جزر القمر' },

  // أوروبا
  { value: 'gb', label: 'المملكة المتحدة' },
  { value: 'fr', label: 'فرنسا' },
  { value: 'de', label: 'ألمانيا' },
  { value: 'it', label: 'إيطاليا' },
  { value: 'es', label: 'إسبانيا' },
  { value: 'pt', label: 'البرتغال' },
  { value: 'nl', label: 'هولندا' },
  { value: 'be', label: 'بلجيكا' },
  { value: 'ch', label: 'سويسرا' },
  { value: 'se', label: 'السويد' },
  { value: 'no', label: 'النرويج' },
  { value: 'dk', label: 'الدنمارك' },
  { value: 'fi', label: 'فنلندا' },
  { value: 'ie', label: 'أيرلندا' },
  { value: 'at', label: 'النمسا' },
  { value: 'gr', label: 'اليونان' },
  { value: 'pl', label: 'بولندا' },
  { value: 'cz', label: 'جمهورية التشيك' },
  { value: 'hu', label: 'المجر' },
  { value: 'ro', label: 'رومانيا' },
  { value: 'bg', label: 'بلغاريا' },
  { value: 'hr', label: 'كرواتيا' },
  { value: 'rs', label: 'صربيا' },
  { value: 'sk', label: 'سلوفاكيا' },
  { value: 'si', label: 'سلوفينيا' },
  { value: 'ee', label: 'إستونيا' },
  { value: 'lv', label: 'لاتفيا' },
  { value: 'lt', label: 'ليتوانيا' },

  // آسيا
  { value: 'cn', label: 'الصين' },
  { value: 'jp', label: 'اليابان' },
  { value: 'kr', label: 'كوريا الجنوبية' },
  { value: 'in', label: 'الهند' },
  { value: 'pk', label: 'باكستان' },
  { value: 'bd', label: 'بنغلاديش' },
  { value: 'id', label: 'إندونيسيا' },
  { value: 'my', label: 'ماليزيا' },
  { value: 'sg', label: 'سنغافورة' },
  { value: 'th', label: 'تايلاند' },
  { value: 'vn', label: 'فيتنام' },
  { value: 'ph', label: 'الفلبين' },
  { value: 'mm', label: 'ميانمار' },
  { value: 'kh', label: 'كمبوديا' },
  { value: 'np', label: 'نيبال' },
  { value: 'lk', label: 'سريلانكا' },
  { value: 'mn', label: 'منغوليا' },
  { value: 'bn', label: 'بروناي' },
  { value: 'mv', label: 'جزر المالديف' },
  { value: 'bt', label: 'بوتان' },
  { value: 'tl', label: 'تيمور الشرقية' },
  { value: 'tr', label: 'تركيا' },
  { value: 'af', label: 'أفغانستان' },

  // أمريكا الشمالية
  { value: 'us', label: 'الولايات المتحدة الأمريكية' },
  { value: 'ca', label: 'كندا' },
  { value: 'mx', label: 'المكسيك' },
  { value: 'gt', label: 'غواتيمالا' },
  { value: 'cu', label: 'كوبا' },
  { value: 'ht', label: 'هايتي' },
  { value: 'do', label: 'جمهورية الدومينيكان' },
  { value: 'hn', label: 'هندوراس' },
  { value: 'ni', label: 'نيكاراغوا' },
  { value: 'sv', label: 'السلفادور' },
  { value: 'cr', label: 'كوستاريكا' },
  { value: 'pa', label: 'بنما' },
  { value: 'bs', label: 'جزر البهاما' },
  { value: 'jm', label: 'جامايكا' },

  // أمريكا الجنوبية
  { value: 'br', label: 'البرازيل' },
  { value: 'ar', label: 'الأرجنتين' },
  { value: 'co', label: 'كولومبيا' },
  { value: 'pe', label: 'بيرو' },
  { value: 've', label: 'فنزويلا' },
  { value: 'cl', label: 'تشيلي' },
  { value: 'ec', label: 'الإكوادور' },
  { value: 'bo', label: 'بوليفيا' },
  { value: 'py', label: 'باراغواي' },
  { value: 'uy', label: 'أوروغواي' },
  { value: 'gy', label: 'غيانا' },
  { value: 'sr', label: 'سورينام' },

  // أفريقيا
  { value: 'za', label: 'جنوب أفريقيا' },
  { value: 'ng', label: 'نيجيريا' },
  { value: 'ke', label: 'كينيا' },
  { value: 'et', label: 'إثيوبيا' },
  { value: 'gh', label: 'غانا' },
  { value: 'ug', label: 'أوغندا' },
  { value: 'tz', label: 'تنزانيا' },
  { value: 'cm', label: 'الكاميرون' },
  { value: 'ci', label: 'ساحل العاج' },
  { value: 'mg', label: 'مدغشقر' },
  { value: 'sn', label: 'السنغال' },
  { value: 'zm', label: 'زامبيا' },
  { value: 'cd', label: 'جمهورية الكونغو الديمقراطية' },
  { value: 'rw', label: 'رواندا' },
  { value: 'bi', label: 'بوروندي' },
  { value: 'mw', label: 'ملاوي' },
  { value: 'na', label: 'ناميبيا' },
  { value: 'bw', label: 'بوتسوانا' },
  { value: 'sz', label: 'إسواتيني' },
  { value: 'ls', label: 'ليسوتو' },
  { value: 'gm', label: 'غامبيا' },
  { value: 'bj', label: 'بنين' },
  { value: 'tg', label: 'توغو' },
  { value: 'sl', label: 'سيراليون' },

  // أوقيانوسيا
  { value: 'au', label: 'أستراليا' },
  { value: 'nz', label: 'نيوزيلندا' },
  { value: 'pg', label: 'بابوا غينيا الجديدة' },
  { value: 'fj', label: 'فيجي' },
  { value: 'sb', label: 'جزر سليمان' },
  { value: 'vu', label: 'فانواتو' },
  { value: 'nc', label: 'كاليدونيا الجديدة' },
  { value: 'pf', label: 'بولينيزيا الفرنسية' }
] as const;

// إنشاء مصفوفة جديدة مع روابط الأعلام فقط
export const countriesWithFlags = countries.map(country => ({
  ...country,
  // استخدام أحدث إصدار من مكتبة الأعلام
  flagIcon: `https://cdn.jsdelivr.net/npm/flag-icons@6.7.0/flags/4x3/${country.value}.svg`,
}));
